# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8bcffc8d785169a9b29a1301e611c5d5a9b19f3bfa1d1ef38769f0675b0e37b44d66e236e28c3fe472c4c0cc278cef849fda658fe59840b2d5952bc080743bd

test:
  secret_key_base: 87a131427597896c933a4e2a43eee28960924d64c2ce59ac483aad9dafd682117bb21867e40446da033ac6499bc23a252c26d9e54d969930a586ec2cf4c5b8cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
